// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCacTpg0PUYLmyeOVVuWxkXr4FABT4RtrA',
    appId: '1:439628752073:web:23a1099db4cb8970d71918',
    messagingSenderId: '439628752073',
    projectId: 'chat-app-caf83',
    authDomain: 'chat-app-caf83.firebaseapp.com',
    storageBucket: 'chat-app-caf83.appspot.com',
    measurementId: 'G-K1XGK274VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfG5WdJxniUDZQpsQdSMJQ_NOsqnpvRXc',
    appId: '1:439628752073:android:cd57cc299d229c23d71918',
    messagingSenderId: '439628752073',
    projectId: 'chat-app-caf83',
    storageBucket: 'chat-app-caf83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClS0RB1TPeh4e0WWd3f_A591Ok2o2mv5w',
    appId: '1:439628752073:ios:ca3b3c9a05b994a3d71918',
    messagingSenderId: '439628752073',
    projectId: 'chat-app-caf83',
    storageBucket: 'chat-app-caf83.appspot.com',
    iosClientId: '439628752073-7trh1oqt4a3qr62k1d5mratt9ga92qff.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClS0RB1TPeh4e0WWd3f_A591Ok2o2mv5w',
    appId: '1:439628752073:ios:b5859d31f33fc4a3d71918',
    messagingSenderId: '439628752073',
    projectId: 'chat-app-caf83',
    storageBucket: 'chat-app-caf83.appspot.com',
    iosClientId: '439628752073-9pblnq11a7vnis99h9mm60tj0tf05c06.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
